### ISSUE TITLE
你好,真机运行崩溃(第四行)

### ISSUE THREAD

**Issue by BaanX** [kimihe/RTC_FaceChat#1]
dyld`__abort_with_payload:
    0x10091a8b4 <+0>:  mov    x16, #0x209
    0x10091a8b8 <+4>:  svc    #0x80
->  0x10091a8bc <+8>:  b.lo   0x10091a8d4               ; <+32>
    0x10091a8c0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x10091a8c4 <+16>: mov    x29, sp
    0x10091a8c8 <+20>: bl     0x10091a100               ; cerror_nocancel
    0x10091a8cc <+24>: mov    sp, x29
    0x10091a8d0 <+28>: ldp    x29, x30, [sp], #0x10
    0x10091a8d4 <+32>: ret

**Comment by kimihe** [comment]
Done!
